### ISSUE TITLE
Unable to generate JWTs that have a sub

### ISSUE THREAD

**Issue by dragonmantank** [Vonage/vonage-php-sdk-core#276]
## Expected Behavior

You should be able to generate a JWT that works with the Conversation API

## Current Behavior

the error:

`Builder#withClaim() is meant to be used for non-registered claims, check the documentation on how to set claim "sub"`

when i remove the "sub" from claims, vonage will thrown error :

`user:error:invalid-user`

## Possible Solution

This looks like something that changed between v3 and v4 of the JWT library we used, and you can no longer set the subscriber as an arbitrary claim. We'll need to change the logic to swap between the two ways.

## Steps to Reproduce (for bugs)

I can't generate jwt from provided claims. this my code:
```php
$keypair = new \Vonage\Client\Credentials\Keypair(file_get_contents(storage_path('voip/vonage/private.key')), env('NEXMO_APPLICATION_ID'));
    $client = new \Vonage\Client($keypair);

    $claims = [
      'exp' => strtotime(date('Y-m-d', strtotime('+24 Hours'))),
      'sub' => 'apg-cs',
      'acl' => [
        'paths' => [
          '/*/users/**' => (object) [],
          '/*/conversations/**' => (object) [],
          '/*/sessions/**' => (object) [],
          '/*/devices/**' => (object) [],
          '/*/image/**' => (object) [],
          '/*/media/**' => (object) [],
          '/*/applications/**' => (object) [],
          '/*/push/**' => (object) [],
          '/*/knocking/**' => (object) [],
          '/*/legs/**' => (object) [],
        ]
      ],
    ];
    $token = $client->generateJwt($claims);
    return $token->toString();
```

## Context

https://stackoverflow.com/questions/66397972/nexmo-error-builderwithclaim-is-meant-to-be-used-for-non-registered-claims-c

## Your Environment

* Version used:
* Environment name and version (e.g. PHP 7.2 on nginx 1.19.1):
* Operating System and version:

**Comment by dragonmantank** [comment]
We are working on figuring out the best fix for this. I just pushed a PR that's going through review to help with this specific case.

The underlying JWT library we use had some major changes in their 4.x release, so for us to have PHP compatibility from 7.2 -> 8.0 we have to actually span two versions of that library. While most things work we're finding places where returned data is slightly different (for example, parsing a token with ACLs returns a `\stdClass` for them under PHP 7.x, but that same claim returns an array on PHP 8.0).

**Comment by rahul1961** [comment]
@dragonmantank thank you so much for an update. looking forward to a fix.

**Comment by rahul1961** [comment]
Hello, @dragonmantank still having the same issue when adding sub in the token. Can you please check, I am using 2.9.2 version as you suggested?

**Comment by rationalthinker1** [comment]
Any update on this one. I still have issues with this one.

**Comment by SecondeJK** [comment]
I've marked this to be re-addressed

**Comment by SecondeJK** [comment]
This is slightly tricky to address, as the Conversations API in the SDK has actually been removed as per the deprecation notice on `1318886a` (By 3.0.0 I had removed it)

My feeling on this is that it's now an unsupported API feature on an unsupported branch, so it may need forking to fix it I'm afraid. I'll see what @dragonmantank thinks.

**Comment by SecondeJK** [comment]
I think we'll need more info here, as I can create a JWT with a sub fine with the current code - can you post new info about the version of the library, the PHP version, the version of `lcobucci/jwt` you're using? (probably) most importantly if there is an API response (not sure whether it's still the ability to add a sub), can you post it?

Conversations is an API that is still in Beta - I think it might be a good idea to switch to a new API for your use case.

**Comment by SecondeJK** [comment]
Closed as no reply, but also with the fact that this API is both not supported as Generally Available or in the SDK.
