### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Typed property Vonage\Messages\Channel\WhatsApp\WhatsAppText::$context must not be accessed before initialization

### ISSUE THREAD

**Issue by suwidadi** [Vonage/vonage-php-sdk-core#504]
I Followed the Example in sending WhatsApp messages in the Readme file, and created the below class:

```php
<?php
require_once(__DIR__.'/vendor/autoload.php');

class SendWa {
    private $client;

    function __construct()
    {
        $this->client = new Vonage\Client(new Vonage\Client\Credentials\Basic('xxx','xxx'),[
            'base_api_url'=> 'https://messages-sandbox.nexmo.com/v1/messages'
        ]);
    }

    function messageSend(){
        $whatsAppText  = new \Vonage\Messages\Channel\WhatsApp\WhatsAppText('xxx','xxx','Test With SDK');
        $response = $this->client->messages()->send($whatsAppText);
    }
}

$sendwa = new SendWa();
$sendwa->messageSend();

```
but throw this error

```code
PHP Fatal error:  Uncaught Error: Typed property Vonage\Messages\Channel\WhatsApp\WhatsAppText::$context must not be accessed before initialization in E:\vonage\vendor\vonage\client-core\src\Messages\Channel\WhatsApp\WhatsAppText.php:32
Stack trace:
#0 E:\vonage\vendor\vonage\client-core\src\Messages\Client.php(26): Vonage\Messages\Channel\WhatsApp\WhatsAppText->toArray()
#1 E:\vonage\index.php(23): Vonage\Messages\Client->send(Object(Vonage\Messages\Channel\WhatsApp\WhatsAppText))
#2 E:\vonage\index.php(28): SendWa->messageSend()
#3 {main}
  thrown in E:\vonage\vendor\vonage\client-core\src\Messages\Channel\WhatsApp\WhatsAppText.php on line 32
```

I'm using PHP 8.3.10. Do you think I should initialize something first?

**Comment by SecondeJK** [comment]
This will be fixed in a release today - it was noticed when this PR was created to fix it: https://github.com/Vonage/vonage-php-sdk-core/pull/500

For a quick workaround, use setContext() on the message and set it to a blank string.

**Comment by SecondeJK** [comment]
Fixed in 4.9.0, thanks for reporting

**Comment by suwidadi** [comment]
Hi, thanks for the support.

i tried to re-run the script but still throw another error

```shell
PHP Warning:  Undefined array key "detail" in /var/www/vonagesdk/vendor/vonage/client-core/src/Messages/ExceptionErrorHandler.php on line 43
PHP Fatal error:  Uncaught Exception: Error Sending Message ->No static resource v1/messages/v1/messages.:  in /var/www/vonagesdk/Sendwa.php:25
Stack trace:
#0 /var/www/vonagesdk/Sendwa.php(31): Sendwa->sendMessage()
#1 {main}
  thrown in /var/www/vonagesdk/Sendwa.php on line 25
```

**Comment by SecondeJK** [comment]
Ah, this is a different issue. The base_url is incorrect in your sample, but at the same time the exception handler needs to deal with the missing detail key. I'll get a patch for this, but in the meantime remove the /v1/messages off the base URL (did you get this from a code snippet or example? Because I'll need to fix that as well)

**Comment by suwidadi** [comment]
Yes, it's a different issue. I create a simple class from the code in the readme file. I didn't dig into the example or snippet.

**Comment by SecondeJK** [comment]
Fixed in 4.10.0

**Comment by suwidadi** [comment]
I didn't remove the /v1/messages off the base URL because I didn't use the base URL. after update the vonage SDK, the error become this:
```php
PHP Fatal error:  Uncaught Vonage\Client\Exception\Request: No static resource v1/messages/v1/messages. in /var/www/vonage/vendor/vonage/client-core/src/Messages/ExceptionErrorHandler.php:49
Stack trace:
#0 /var/www/vonage/vendor/vonage/client-core/src/Client/APIResource.php(301): Vonage\Messages\ExceptionErrorHandler->__invoke()
#1 /var/www/vonage/vendor/vonage/client-core/src/Client/APIResource.php(123): Vonage\Client\APIResource->getException()
#2 /var/www/vonage/vendor/vonage/client-core/src/Messages/Client.php(26): Vonage\Client\APIResource->create()
#3 /var/www/vonage/Sendwa.php(115): Vonage\Messages\Client->send()
#4 /var/www/vonage/Sendwa.php(153): Sendwa->vonageSend()
#5 {main}
  thrown in /var/www/vonage/vendor/vonage/client-core/src/Messages/ExceptionErrorHandler.php on line 49
```
